SQL> DESC DEMO_STUDENTS;
 Name                                      Null?    Type
 ----------------------------------------- -------- ----------------------------
 SNO                                                NUMBER(5)
 SNAME                                              VARCHAR2(10)
 TOTAL                                              NUMBER(5)
 PERCENTAGE                                         NUMBER(5)
 RESULT                                             VARCHAR2(10)
